### ISSUE TITLE
Can you add a demo page?

### ISSUE THREAD

**Issue by ustincameron** [ZenLiuCN/PDFForm#1]
Looking to implement this within a React app.

**Comment by ZenLiuCN** [comment]
This is just a background lib, if use it with some application. 
you must dothings blow:
1. make a PDF form with fields
2. make a page with specified fields for user to fill value with.
3. after user filled values for fields, fill it use this library or use [phihag/pdfform.js](https://github.com/phihag/pdfform.js) for js only.

see [demo](https://phihag.github.io/pdfform.js/docs/demo.html) this is just the same.  cause of this library just pure TS port of it
